/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file           : main.h
 * @brief          : Header for main.c (application-wide types and constants).
 *
 * This header collects:
 *  - Global configuration macros for pack topology and timing
 *  - Pack/module data structures (cell/thermistor readings, summaries)
 *  - CAN message buffers used by the application layer
 *  - MCU pin definitions generated by CubeMX
 *
 * Conventions:
 *  - Voltages and temperatures are stored as integers (units noted per field).
 *  - Array sizes derive from NUM_MOD / NUM_CELL_PER_MOD / NUM_THERM_PER_MOD.
 *  - Timing values are in milliseconds unless otherwise stated.
 ******************************************************************************
 */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f1xx_hal.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "stdbool.h"
/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */

/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */

/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */

/* USER CODE END EFP */

/* Private defines -----------------------------------------------------------*/
#define Shunt_PIN_FOR_2A_Pin GPIO_PIN_2
#define Shunt_PIN_FOR_2A_GPIO_Port GPIOC
#define CONTACTOR_SENSE_Pin GPIO_PIN_2
#define CONTACTOR_SENSE_GPIO_Port GPIOA
#define LTC_nCS_Pin GPIO_PIN_4
#define LTC_nCS_GPIO_Port GPIOA
#define HV_SENSE_Pin GPIO_PIN_5
#define HV_SENSE_GPIO_Port GPIOC
#define MCU_SHUTDOWN_SIGNAL_Pin GPIO_PIN_1
#define MCU_SHUTDOWN_SIGNAL_GPIO_Port GPIOB
#define MCU_HEARTBEAT_LED_Pin GPIO_PIN_6
#define MCU_HEARTBEAT_LED_GPIO_Port GPIOC
#define EEPROM_nCS_Pin GPIO_PIN_15
#define EEPROM_nCS_GPIO_Port GPIOA

/* USER CODE BEGIN Private defines */
#define NUM_MOD					10
#define NUM_CELL_PER_MOD	 	14
#define NUM_CELLS				(NUM_MOD*NUM_CELL_PER_MOD)	
#define NUM_THERM_PER_MOD		10
#define NUM_THERM_TOTAL			(NUM_MOD*NUM_THERM_PER_MOD)
#define NUM_AUX_GROUP			6
#define NUM_AUXES				(NUM_MOD*NUM_AUX_GROUP)
#define MAX_CELL_CAPACITY 		3000
#define MAX_BATTERY_CAPACITY 	(NUM_MOD* MAX_CELL_CAPACITY)
/* USER CODE END Private defines */


#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
