/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file           : main.h
 * @brief          : Header for main.c (application-wide types and constants).
 *
 * This header collects:
 *  - Global configuration macros for pack topology and timing
 *  - Pack/module data structures (cell/thermistor readings, summaries)
 *  - CAN message buffers used by the application layer
 *  - MCU pin definitions generated by CubeMX
 *
 * Conventions:
 *  - Voltages and temperatures are stored as integers (units noted per field).
 *  - Array sizes derive from NUM_MOD / NUM_CELL_PER_MOD / NUM_THERM_PER_MOD.
 *  - Timing values are in milliseconds unless otherwise stated.
 ******************************************************************************
 */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f1xx_hal.h"
/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "stdbool.h"
/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */

/* USER CODE BEGIN Private defines */
/* ===== Application Configuration ============================================
 * The following macros describe the pack topology, measurement group sizes,
 * and task cadence. They are used across modules to dimension arrays and
 * control periodic behavior.
 *
 * Notes:
 *  - NUM_MOD: number of slave boards (modules) in the daisy chain.
 *  - NUM_CELL_PER_MOD: series cells monitored per module.
 *  - NUM_THERM_PER_MOD: thermistors per module (external to ADBMS AUX count).
 *  - NUM_AUX_GROUP * NUM_MOD = total AUX channels returned by RDAUX pages.
 *  - CYCLETIME_CAP caps the main BMS loop/update period (ms).
 *  - BALANCE is a feature toggle (0 = disabled at compile time).
 *  - MAX_*_CAPACITY are nominal capacities (mAh) used for SoC/estimation.
 */
/* USER CODE END Private defines */





/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */

/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */

/* USER CODE END EFP */

/* Private defines -----------------------------------------------------------*/
/* ===== MCU Pin Mapping (auto-generated by CubeMX) ============================
 * These GPIO aliases are used by board support code to access peripherals.
 * Adjust in .ioc and regenerate if hardware changes.
 */
#define Shunt_PIN_FOR_2A_Pin GPIO_PIN_2
#define Shunt_PIN_FOR_2A_GPIO_Port GPIOC
#define LTC_nCS_Pin GPIO_PIN_4
#define LTC_nCS_GPIO_Port GPIOA
#define MCU_ADC_VSENSE_Pin GPIO_PIN_5
#define MCU_ADC_VSENSE_GPIO_Port GPIOC
#define MCU_SHUTDOWN_SIGNAL_Pin GPIO_PIN_1
#define MCU_SHUTDOWN_SIGNAL_GPIO_Port GPIOB
#define MCU_HEARTBEAT_LED_Pin GPIO_PIN_6
#define MCU_HEARTBEAT_LED_GPIO_Port GPIOC

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
